// Auto-generated from src/imports/Global_RSS_Feeds.csv. Do not edit by hand.
export type IntlFeed = {
  name: string;
  nameFa: string;
  url: string;
  country: string;
  countryName: string;
  flag: string;
  language: string;
  category: string;
  categoryFa: string;
  website: string;
};

export const INTL_FEEDS: IntlFeed[] = [
  {
    "name": "BBC News",
    "nameFa": "بی‌بی‌سی نیوز",
    "url": "http://feeds.bbci.co.uk/news/rss.xml",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.bbc.com"
  },
  {
    "name": "BBC News",
    "nameFa": "بی‌بی‌سی نیوز",
    "url": "http://feeds.bbci.co.uk/news/politics/rss.xml",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "politics",
    "categoryFa": "سیاسی",
    "website": "https://www.bbc.com"
  },
  {
    "name": "BBC News",
    "nameFa": "بی‌بی‌سی نیوز",
    "url": "http://feeds.bbci.co.uk/news/technology/rss.xml",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.bbc.com"
  },
  {
    "name": "BBC News",
    "nameFa": "بی‌بی‌سی نیوز",
    "url": "http://feeds.bbci.co.uk/news/sport/rss.xml",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "sports",
    "categoryFa": "ورزشی",
    "website": "https://www.bbc.com"
  },
  {
    "name": "CNN",
    "nameFa": "سی‌ان‌ان",
    "url": "http://rss.cnn.com/rss/edition.rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.cnn.com"
  },
  {
    "name": "CNN",
    "nameFa": "سی‌ان‌ان",
    "url": "http://rss.cnn.com/rss/money_news_international.rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://www.cnn.com"
  },
  {
    "name": "CNN",
    "nameFa": "سی‌ان‌ان",
    "url": "http://rss.cnn.com/rss/edition_technology.rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.cnn.com"
  },
  {
    "name": "Al Jazeera",
    "nameFa": "الجزیره",
    "url": "https://www.aljazeera.com/xml/rss/all.xml",
    "country": "QA",
    "countryName": "قطر",
    "flag": "🇶🇦",
    "language": "انگلیسی/عربی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.aljazeera.com"
  },
  {
    "name": "Reuters",
    "nameFa": "رویترز",
    "url": "https://openrss.org/reuters.com/world",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.reuters.com"
  },
  {
    "name": "Reuters",
    "nameFa": "رویترز",
    "url": "https://openrss.org/reuters.com/business",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://www.reuters.com"
  },
  {
    "name": "Associated Press (AP)",
    "nameFa": "آسوشیتد پرس",
    "url": "http://associated-press.s3-website-us-east-1.amazonaws.com/topnews.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://apnews.com"
  },
  {
    "name": "AFP",
    "nameFa": "فرانس پرس",
    "url": "https://openrss.org/afp.com",
    "country": "FR",
    "countryName": "فرانسه",
    "flag": "🇫🇷",
    "language": "فرانسوی/انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.afp.com"
  },
  {
    "name": "Bloomberg",
    "nameFa": "بلومبرگ",
    "url": "https://www.bloomberg.com/politics/feeds/site.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.bloomberg.com"
  },
  {
    "name": "Bloomberg",
    "nameFa": "بلومبرگ",
    "url": "https://www.bloomberg.com/feeds/bview/rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://www.bloomberg.com"
  },
  {
    "name": "DW (Deutsche Welle)",
    "nameFa": "دویچه وله",
    "url": "https://rss.dw.com/xml/rss-en-all",
    "country": "DE",
    "countryName": "آلمان",
    "flag": "🇩🇪",
    "language": "آلمانی/انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.dw.com"
  },
  {
    "name": "DW (Deutsche Welle)",
    "nameFa": "دویچه وله",
    "url": "https://rss.dw.com/xml/rss-en-bus",
    "country": "DE",
    "countryName": "آلمان",
    "flag": "🇩🇪",
    "language": "آلمانی/انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://www.dw.com"
  },
  {
    "name": "France 24",
    "nameFa": "فرانس ۲۴",
    "url": "https://www.france24.com/en/rss",
    "country": "FR",
    "countryName": "فرانسه",
    "flag": "🇫🇷",
    "language": "فرانسوی/انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.france24.com"
  },
  {
    "name": "NHK World",
    "nameFa": "ان‌اچ‌کی ورد",
    "url": "https://www3.nhk.or.jp/nhkworld/rd/rss/english.xml",
    "country": "JP",
    "countryName": "ژاپن",
    "flag": "🇯🇵",
    "language": "ژاپنی/انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www3.nhk.or.jp/nhkworld/"
  },
  {
    "name": "TASS",
    "nameFa": "تاس",
    "url": "https://tass.com/rss/v2.xml",
    "country": "RU",
    "countryName": "روسیه",
    "flag": "🇷🇺",
    "language": "روسی/انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://tass.com"
  },
  {
    "name": "TASS",
    "nameFa": "تاس",
    "url": "https://tass.com/rss/v2.xml?section=economy",
    "country": "RU",
    "countryName": "روسیه",
    "flag": "🇷🇺",
    "language": "روسی/انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://tass.com"
  },
  {
    "name": "Xinhua",
    "nameFa": "شینهوا",
    "url": "http://www.xinhuanet.com/english/rss/worldrss.xml",
    "country": "CN",
    "countryName": "چین",
    "flag": "🇨🇳",
    "language": "چینی/انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "http://www.xinhuanet.com/english/"
  },
  {
    "name": "ANI News",
    "nameFa": "ای‌ان‌آی نیوز",
    "url": "https://aninews.in/rss/feed/category/national/politics.xml",
    "country": "IN",
    "countryName": "هند",
    "flag": "🇮🇳",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.aninews.in"
  },
  {
    "name": "EFE",
    "nameFa": "افه",
    "url": "https://www.efe.com/efe/english/4/rss",
    "country": "ES",
    "countryName": "اسپانیا",
    "flag": "🇪🇸",
    "language": "اسپانیایی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.efe.com"
  },
  {
    "name": "The New York Times",
    "nameFa": "نیویورک تایمز",
    "url": "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.nytimes.com"
  },
  {
    "name": "The New York Times",
    "nameFa": "نیویورک تایمز",
    "url": "https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "politics",
    "categoryFa": "سیاسی",
    "website": "https://www.nytimes.com"
  },
  {
    "name": "The New York Times",
    "nameFa": "نیویورک تایمز",
    "url": "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.nytimes.com"
  },
  {
    "name": "The Guardian",
    "nameFa": "گاردین",
    "url": "https://www.theguardian.com/world/rss",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.theguardian.com"
  },
  {
    "name": "The Guardian",
    "nameFa": "گاردین",
    "url": "https://www.theguardian.com/business/rss",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://www.theguardian.com"
  },
  {
    "name": "The Washington Post",
    "nameFa": "واشینگتن پست",
    "url": "https://feeds.washingtonpost.com/rss/world",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.washingtonpost.com"
  },
  {
    "name": "The Washington Post",
    "nameFa": "واشینگتن پست",
    "url": "https://feeds.washingtonpost.com/rss/politics",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "politics",
    "categoryFa": "سیاسی",
    "website": "https://www.washingtonpost.com"
  },
  {
    "name": "The Washington Post",
    "nameFa": "واشینگتن پست",
    "url": "https://feeds.washingtonpost.com/rss/business",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://www.washingtonpost.com"
  },
  {
    "name": "Financial Times",
    "nameFa": "فایننشال تایمز",
    "url": "https://www.ft.com/rss/home",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.ft.com"
  },
  {
    "name": "Financial Times",
    "nameFa": "فایننشال تایمز",
    "url": "https://www.ft.com/markets?format=rss",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://www.ft.com"
  },
  {
    "name": "The Economist",
    "nameFa": "اکونومیست",
    "url": "https://www.economist.com/business-and-finance/rss.xml",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.economist.com"
  },
  {
    "name": "The Economist",
    "nameFa": "اکونومیست",
    "url": "http://www.economist.com/feeds/print-sections/80/science-and-technology.xml",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.economist.com"
  },
  {
    "name": "Wall Street Journal",
    "nameFa": "وال استریت ژورنال",
    "url": "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.wsj.com"
  },
  {
    "name": "Wall Street Journal",
    "nameFa": "وال استریت ژورنال",
    "url": "https://feeds.a.dj.com/rss/RSSMarketsMain.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://www.wsj.com"
  },
  {
    "name": "Le Monde",
    "nameFa": "لوموند",
    "url": "https://www.lemonde.fr/rss/une.xml",
    "country": "FR",
    "countryName": "فرانسه",
    "flag": "🇫🇷",
    "language": "فرانسوی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.lemonde.fr"
  },
  {
    "name": "Der Spiegel",
    "nameFa": "اشپیگل",
    "url": "https://www.spiegel.de/schlagzeilen/index.rss",
    "country": "DE",
    "countryName": "آلمان",
    "flag": "🇩🇪",
    "language": "آلمانی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.spiegel.de"
  },
  {
    "name": "El País",
    "nameFa": "ال پائیس",
    "url": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
    "country": "ES",
    "countryName": "اسپانیا",
    "flag": "🇪🇸",
    "language": "اسپانیایی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://elpais.com"
  },
  {
    "name": "South China Morning Post",
    "nameFa": "ساوت چاینا مورنینگ پست",
    "url": "https://www.scmp.com/rss/5/feed",
    "country": "HK",
    "countryName": "هنگ‌کنگ",
    "flag": "🇭🇰",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.scmp.com"
  },
  {
    "name": "South China Morning Post",
    "nameFa": "ساوت چاینا مورنینگ پست",
    "url": "https://www.scmp.com/rss/92/feed",
    "country": "HK",
    "countryName": "هنگ‌کنگ",
    "flag": "🇭🇰",
    "language": "انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://www.scmp.com"
  },
  {
    "name": "The Independent",
    "nameFa": "ایندیپندنت",
    "url": "https://www.independent.co.uk/news/world/rss",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.independent.co.uk"
  },
  {
    "name": "The Independent",
    "nameFa": "ایندیپندنت",
    "url": "https://www.independent.co.uk/news/business/rss",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://www.independent.co.uk"
  },
  {
    "name": "The Telegraph",
    "nameFa": "تلگراف",
    "url": "https://www.telegraph.co.uk/rss.xml",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.telegraph.co.uk"
  },
  {
    "name": "Frankfurter Allgemeine",
    "nameFa": "فرانکفورتر آلگماینه",
    "url": "https://www.faz.net/rss/aktuell/",
    "country": "DE",
    "countryName": "آلمان",
    "flag": "🇩🇪",
    "language": "آلمانی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.faz.net"
  },
  {
    "name": "Frankfurter Allgemeine",
    "nameFa": "فرانکفورتر آلگماینه",
    "url": "https://www.faz.net/rss/aktuell/wirtschaft/",
    "country": "DE",
    "countryName": "آلمان",
    "flag": "🇩🇪",
    "language": "آلمانی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://www.faz.net"
  },
  {
    "name": "La Repubblica",
    "nameFa": "لا رپوبلیکا",
    "url": "https://www.repubblica.it/rss/homepage/rss2.0.xml",
    "country": "IT",
    "countryName": "ایتالیا",
    "flag": "🇮🇹",
    "language": "ایتالیایی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.repubblica.it"
  },
  {
    "name": "La Repubblica",
    "nameFa": "لا رپوبلیکا",
    "url": "https://www.repubblica.it/rss/politica/rss2.0.xml",
    "country": "IT",
    "countryName": "ایتالیا",
    "flag": "🇮🇹",
    "language": "ایتالیایی",
    "category": "politics",
    "categoryFa": "سیاسی",
    "website": "https://www.repubblica.it"
  },
  {
    "name": "Forbes",
    "nameFa": "فوربز",
    "url": "https://www.forbes.com/business/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.forbes.com"
  },
  {
    "name": "Forbes",
    "nameFa": "فوربز",
    "url": "https://www.forbes.com/investing/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://www.forbes.com"
  },
  {
    "name": "Council on Foreign Relations (CFR)",
    "nameFa": "شورای روابط خارجی",
    "url": "https://www.cfr.org/rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.cfr.org"
  },
  {
    "name": "Brookings Institution",
    "nameFa": "مؤسسه بروکینگز",
    "url": "https://www.brookings.edu/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.brookings.edu"
  },
  {
    "name": "Brookings Institution",
    "nameFa": "مؤسسه بروکینگز",
    "url": "https://www.brookings.edu/topic/foreign-policy/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "politics",
    "categoryFa": "سیاسی",
    "website": "https://www.brookings.edu"
  },
  {
    "name": "Brookings Institution",
    "nameFa": "مؤسسه بروکینگز",
    "url": "https://www.brookings.edu/topic/global-economy/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://www.brookings.edu"
  },
  {
    "name": "RAND Corporation",
    "nameFa": "شرکت رند",
    "url": "https://www.rand.org/pubs.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.rand.org"
  },
  {
    "name": "Chatham House",
    "nameFa": "چتم هاوس",
    "url": "https://www.chathamhouse.org/rss.xml",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.chathamhouse.org"
  },
  {
    "name": "Carnegie Endowment",
    "nameFa": "موقوفه کارنگی",
    "url": "https://carnegieendowment.org/rss/all",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://carnegieendowment.org"
  },
  {
    "name": "Wilson Center",
    "nameFa": "مرکز ویلسون",
    "url": "https://www.wilsoncenter.org/rss/news",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.wilsoncenter.org"
  },
  {
    "name": "IISS",
    "nameFa": "مؤسسه مطالعات استراتژیک",
    "url": "https://www.iiss.org/rss/commentary",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.iiss.org"
  },
  {
    "name": "Foreign Policy",
    "nameFa": "فارن پالیسی",
    "url": "https://foreignpolicy.com/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://foreignpolicy.com"
  },
  {
    "name": "Foreign Affairs",
    "nameFa": "فارن افرز",
    "url": "https://www.foreignaffairs.com/rss.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.foreignaffairs.com"
  },
  {
    "name": "The Atlantic",
    "nameFa": "آتلانتیک",
    "url": "https://www.theatlantic.com/feed/all/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.theatlantic.com"
  },
  {
    "name": "The Atlantic",
    "nameFa": "آتلانتیک",
    "url": "https://www.theatlantic.com/feed/channel/politics/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "politics",
    "categoryFa": "سیاسی",
    "website": "https://www.theatlantic.com"
  },
  {
    "name": "Project Syndicate",
    "nameFa": "پراجکت سندیکیت",
    "url": "https://www.project-syndicate.org/rss",
    "country": "CZ",
    "countryName": "چک",
    "flag": "🇨🇿",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.project-syndicate.org"
  },
  {
    "name": "Stratfor",
    "nameFa": "استراتفور",
    "url": "https://www.ranenetwork.com/feed",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://worldview.stratfor.com"
  },
  {
    "name": "SIPRI",
    "nameFa": "سیپری",
    "url": "https://www.sipri.org/rss.xml",
    "country": "SE",
    "countryName": "سوئد",
    "flag": "🇸🇪",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.sipri.org"
  },
  {
    "name": "CSIS",
    "nameFa": "سی‌اس‌آی‌اس",
    "url": "https://www.csis.org/rss.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.csis.org"
  },
  {
    "name": "ECFR",
    "nameFa": "شورای روابط خارجی اروپا",
    "url": "https://ecfr.eu/feed/",
    "country": "EU",
    "countryName": "اتحادیه اروپا",
    "flag": "🇪🇺",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://ecfr.eu"
  },
  {
    "name": "Crisis Group",
    "nameFa": "گروه بحران",
    "url": "https://www.crisisgroup.org/rss.xml",
    "country": "BE",
    "countryName": "بلژیک",
    "flag": "🇧🇪",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.crisisgroup.org"
  },
  {
    "name": "CNBC",
    "nameFa": "سی‌ان‌بی‌سی",
    "url": "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.cnbc.com"
  },
  {
    "name": "CNBC",
    "nameFa": "سی‌ان‌بی‌سی",
    "url": "https://www.cnbc.com/id/10000664/device/rss/rss.html",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://www.cnbc.com"
  },
  {
    "name": "MarketWatch",
    "nameFa": "مارکت واچ",
    "url": "http://feeds.marketwatch.com/marketwatch/topstories/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.marketwatch.com"
  },
  {
    "name": "MarketWatch",
    "nameFa": "مارکت واچ",
    "url": "http://feeds.marketwatch.com/marketwatch/marketupdate/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://www.marketwatch.com"
  },
  {
    "name": "Seeking Alpha",
    "nameFa": "سیکینگ آلفا",
    "url": "https://seekingalpha.com/market_news.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://seekingalpha.com"
  },
  {
    "name": "Seeking Alpha",
    "nameFa": "سیکینگ آلفا",
    "url": "https://seekingalpha.com/analysis.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://seekingalpha.com"
  },
  {
    "name": "Investing.com",
    "nameFa": "اینوستینگ",
    "url": "https://www.investing.com/rss/news.rss",
    "country": "INT",
    "countryName": "بین‌المللی",
    "flag": "🌐",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.investing.com"
  },
  {
    "name": "Investing.com",
    "nameFa": "اینوستینگ",
    "url": "https://www.investing.com/rss/news_25.rss",
    "country": "INT",
    "countryName": "بین‌المللی",
    "flag": "🌐",
    "language": "انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://www.investing.com"
  },
  {
    "name": "The Motley Fool",
    "nameFa": "ماتلی فول",
    "url": "https://www.fool.com/about/rss-feeds/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.fool.com"
  },
  {
    "name": "ZeroHedge",
    "nameFa": "زیرو هج",
    "url": "http://feeds.feedburner.com/zerohedge/feed",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.zerohedge.com"
  },
  {
    "name": "Barron's",
    "nameFa": "بارونز",
    "url": "https://www.barrons.com/feed",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.barrons.com"
  },
  {
    "name": "Fortune",
    "nameFa": "فورچون",
    "url": "https://fortune.com/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://fortune.com"
  },
  {
    "name": "Business Insider",
    "nameFa": "بیزنس اینسایدر",
    "url": "https://www.businessinsider.com/rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.businessinsider.com"
  },
  {
    "name": "Business Insider",
    "nameFa": "بیزنس اینسایدر",
    "url": "https://www.businessinsider.com/finance/rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://www.businessinsider.com"
  },
  {
    "name": "HBR (Harvard Business Review)",
    "nameFa": "اچ‌بی‌آر",
    "url": "https://hbr.org/rss/management",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://hbr.org"
  },
  {
    "name": "HBR (Harvard Business Review)",
    "nameFa": "اچ‌بی‌آر",
    "url": "https://hbr.org/topic/economy?format=rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "business",
    "categoryFa": "اقتصادی",
    "website": "https://hbr.org"
  },
  {
    "name": "IMF Blog",
    "nameFa": "صندوق بین‌المللی پول",
    "url": "https://www.imf.org/en/Blogs/RSS",
    "country": "INT",
    "countryName": "بین‌المللی",
    "flag": "🌐",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.imf.org"
  },
  {
    "name": "World Bank Blog",
    "nameFa": "بانک جهانی",
    "url": "https://blogs.worldbank.org/en/rss.xml",
    "country": "INT",
    "countryName": "بین‌المللی",
    "flag": "🌐",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://worldbank.org"
  },
  {
    "name": "Yahoo Finance",
    "nameFa": "یاهو فایننس",
    "url": "https://finance.yahoo.com/news/rssindex",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://finance.yahoo.com"
  },
  {
    "name": "TechCrunch",
    "nameFa": "تک‌کرانچ",
    "url": "https://techcrunch.com/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://techcrunch.com"
  },
  {
    "name": "TechCrunch",
    "nameFa": "تک‌کرانچ",
    "url": "https://techcrunch.com/category/artificial-intelligence/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://techcrunch.com"
  },
  {
    "name": "Wired",
    "nameFa": "وایرد",
    "url": "https://www.wired.com/feed/rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.wired.com"
  },
  {
    "name": "Wired",
    "nameFa": "وایرد",
    "url": "https://www.wired.com/feed/category/security/latest/rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.wired.com"
  },
  {
    "name": "The Verge",
    "nameFa": "ورج",
    "url": "https://www.theverge.com/rss/index.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.theverge.com"
  },
  {
    "name": "The Verge",
    "nameFa": "ورج",
    "url": "https://www.theverge.com/policy/rss/index.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.theverge.com"
  },
  {
    "name": "Ars Technica",
    "nameFa": "آرس تکنیکا",
    "url": "https://feeds.arstechnica.com/arstechnica/index",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://arstechnica.com"
  },
  {
    "name": "MIT Tech Review",
    "nameFa": "ام‌آی‌تی تک ریویو",
    "url": "https://www.technologyreview.com/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.technologyreview.com"
  },
  {
    "name": "IEEE Spectrum",
    "nameFa": "آی‌تریپل‌ئی اسپکتروم",
    "url": "https://spectrum.ieee.org/rss/fulltext",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://spectrum.ieee.org"
  },
  {
    "name": "Nature News",
    "nameFa": "نیچر",
    "url": "https://www.nature.com/nature.rss",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "science",
    "categoryFa": "علمی",
    "website": "https://www.nature.com"
  },
  {
    "name": "Science Magazine",
    "nameFa": "ساینس",
    "url": "https://www.science.org/rss/news_current.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "science",
    "categoryFa": "علمی",
    "website": "https://www.science.org"
  },
  {
    "name": "New Scientist",
    "nameFa": "نیو ساینتیست",
    "url": "https://www.newscientist.com/feed/home/",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "science",
    "categoryFa": "علمی",
    "website": "https://www.newscientist.com"
  },
  {
    "name": "ZDNet",
    "nameFa": "زددی‌نت",
    "url": "https://www.zdnet.com/news/rss.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.zdnet.com"
  },
  {
    "name": "VentureBeat",
    "nameFa": "ونچربیت",
    "url": "https://venturebeat.com/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://venturebeat.com"
  },
  {
    "name": "Engadget",
    "nameFa": "انگجت",
    "url": "https://www.engadget.com/rss.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.engadget.com"
  },
  {
    "name": "Gizmodo",
    "nameFa": "گیزمودو",
    "url": "https://gizmodo.com/rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://gizmodo.com"
  },
  {
    "name": "Hacker News",
    "nameFa": "هکر نیوز",
    "url": "https://hnrss.org/frontpage",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://news.ycombinator.com"
  },
  {
    "name": "Slashdot",
    "nameFa": "اسلش‌دات",
    "url": "http://rss.slashdot.org/Slashdot/slashdotMain",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://slashdot.org"
  },
  {
    "name": "Scientific American",
    "nameFa": "ساینتیفیک امریکن",
    "url": "http://rss.sciam.com/ScientificAmerican-Global",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "science",
    "categoryFa": "علمی",
    "website": "https://www.scientificamerican.com"
  },
  {
    "name": "CNET",
    "nameFa": "سی‌نت",
    "url": "https://www.cnet.com/rss/news/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.cnet.com"
  },
  {
    "name": "InfoWorld",
    "nameFa": "اینفو ورد",
    "url": "https://www.infoworld.com/index.rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.infoworld.com"
  },
  {
    "name": "Popular Science",
    "nameFa": "پاپ ساینس",
    "url": "https://www.popsci.com/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "science",
    "categoryFa": "علمی",
    "website": "https://www.popsci.com"
  },
  {
    "name": "Quanta Magazine",
    "nameFa": "کوانتا مگزین",
    "url": "https://www.quantamagazine.org/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "science",
    "categoryFa": "علمی",
    "website": "https://www.quantamagazine.org"
  },
  {
    "name": "BBC Persian",
    "nameFa": "بی‌بی‌سی فارسی",
    "url": "https://www.bbc.com/persian/index.xml",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "فارسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.bbc.com/persian"
  },
  {
    "name": "VOA Persian",
    "nameFa": "صدای آمریکا",
    "url": "https://ir.voanews.com/rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "فارسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://ir.voanews.com"
  },
  {
    "name": "Radio Farda",
    "nameFa": "رادیو فردا",
    "url": "https://www.radiofarda.com/rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "فارسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.radiofarda.com"
  },
  {
    "name": "Iran International",
    "nameFa": "ایران اینترنشنال",
    "url": "https://www.iranintl.com/rss",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "فارسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.iranintl.com"
  },
  {
    "name": "DW Persian",
    "nameFa": "دویچه وله فارسی",
    "url": "https://rss.dw.com/xml/rss-fa-all",
    "country": "DE",
    "countryName": "آلمان",
    "flag": "🇩🇪",
    "language": "فارسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.dw.com/fa-ir"
  },
  {
    "name": "Euronews Persian",
    "nameFa": "یورونیوز فارسی",
    "url": "https://per.euronews.com/rss?format=all",
    "country": "FR",
    "countryName": "فرانسه",
    "flag": "🇫🇷",
    "language": "فارسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://per.euronews.com"
  },
  {
    "name": "Al-Monitor",
    "nameFa": "المانیتور",
    "url": "https://www.al-monitor.com/rss",
    "country": "ME",
    "countryName": "خاورمیانه",
    "flag": "🌍",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.al-monitor.com"
  },
  {
    "name": "Middle East Eye",
    "nameFa": "میدل ایست آی",
    "url": "https://www.middleeasteye.net/rss",
    "country": "ME",
    "countryName": "خاورمیانه",
    "flag": "🌍",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.middleeasteye.net"
  },
  {
    "name": "Arab News",
    "nameFa": "عرب نیوز",
    "url": "https://www.arabnews.com/rss.xml",
    "country": "SA",
    "countryName": "عربستان",
    "flag": "🇸🇦",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.arabnews.com"
  },
  {
    "name": "Gulf News",
    "nameFa": "گلف نیوز",
    "url": "https://gulfnews.com/rss",
    "country": "AE",
    "countryName": "امارات",
    "flag": "🇦🇪",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://gulfnews.com"
  },
  {
    "name": "Haaretz",
    "nameFa": "هاآرتص",
    "url": "https://www.haaretz.com/srv/haaretz-latest-rss",
    "country": "IL",
    "countryName": "اسرائیل",
    "flag": "🇮🇱",
    "language": "انگلیسی/عبری",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.haaretz.com"
  },
  {
    "name": "Jerusalem Post",
    "nameFa": "جروزالم پست",
    "url": "https://www.jpost.com/rss/rssfeedsfrontpage.aspx",
    "country": "IL",
    "countryName": "اسرائیل",
    "flag": "🇮🇱",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.jpost.com"
  },
  {
    "name": "Daily Sabah",
    "nameFa": "دیلی صباح",
    "url": "https://www.dailysabah.com/rss",
    "country": "TR",
    "countryName": "ترکیه",
    "flag": "🇹🇷",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.dailysabah.com"
  },
  {
    "name": "Hurriyet Daily",
    "nameFa": "حریت دیلی",
    "url": "https://www.hurriyetdailynews.com/rss",
    "country": "TR",
    "countryName": "ترکیه",
    "flag": "🇹🇷",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.hurriyetdailynews.com"
  },
  {
    "name": "AKIpress",
    "nameFa": "آکی پرس",
    "url": "https://akipress.com/rss/",
    "country": "KG",
    "countryName": "قرقیزستان",
    "flag": "🇰🇬",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://akipress.com"
  },
  {
    "name": "Fergana News",
    "nameFa": "فرغانه نیوز",
    "url": "https://fergana.agency/rss.php",
    "country": "ME",
    "countryName": "منطقه",
    "flag": "🌍",
    "language": "روسی/انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://fergana.agency"
  },
  {
    "name": "Radio Azattyk",
    "nameFa": "رادیو آزاتیک",
    "url": "https://www.azattyk.org/rssfeeds",
    "country": "KG",
    "countryName": "قرقیزستان",
    "flag": "🇰🇬",
    "language": "قرقیزی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.azattyk.org"
  },
  {
    "name": "Kun.uz",
    "nameFa": "کون نیوز",
    "url": "https://kun.uz/en/rss",
    "country": "UZ",
    "countryName": "ازبکستان",
    "flag": "🇺🇿",
    "language": "ازبکی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://kun.uz/en"
  },
  {
    "name": "24.kg",
    "nameFa": "۲۴ کی‌جی",
    "url": "https://24.kg/rss/",
    "country": "KG",
    "countryName": "قرقیزستان",
    "flag": "🇰🇬",
    "language": "روسی/انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://24.kg"
  },
  {
    "name": "Sky News",
    "nameFa": "اسکای نیوز",
    "url": "https://feeds.skynews.com/feeds/rss/home.xml",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://news.sky.com"
  },
  {
    "name": "ABC News",
    "nameFa": "ای‌بی‌سی نیوز",
    "url": "https://abcnews.go.com/abcnews/topstories",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://abcnews.go.com"
  },
  {
    "name": "CBS News",
    "nameFa": "سی‌بی‌اس نیوز",
    "url": "https://www.cbsnews.com/latest/rss/main",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.cbsnews.com"
  },
  {
    "name": "NBC News",
    "nameFa": "ان‌بی‌سی نیوز",
    "url": "https://feeds.nbcnews.com/nbcnews/public/world",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.nbcnews.com"
  },
  {
    "name": "Euronews English",
    "nameFa": "یورونیوز انگلیسی",
    "url": "https://www.euronews.com/rss?format=all",
    "country": "EU",
    "countryName": "اروپا",
    "flag": "🇪🇺",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.euronews.com"
  },
  {
    "name": "Yonhap News",
    "nameFa": "یونهاپ",
    "url": "https://en.yna.co.kr/rss/news.xml",
    "country": "KR",
    "countryName": "کره جنوبی",
    "flag": "🇰🇷",
    "language": "کره‌ای/انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://en.yna.co.kr"
  },
  {
    "name": "Anadolu Agency",
    "nameFa": "آنادولو",
    "url": "https://www.aa.com.tr/en/rss/defaultxml.xml",
    "country": "TR",
    "countryName": "ترکیه",
    "flag": "🇹🇷",
    "language": "ترکی/انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.aa.com.tr/en"
  },
  {
    "name": "Bernama",
    "nameFa": "برناما",
    "url": "https://www.bernama.com/en/rss.php",
    "country": "MY",
    "countryName": "مالزی",
    "flag": "🇲🇾",
    "language": "مالایی/انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.bernama.com"
  },
  {
    "name": "Antara News",
    "nameFa": "آنتارا",
    "url": "https://en.antaranews.com/rss/news.xml",
    "country": "ID",
    "countryName": "اندونزی",
    "flag": "🇮🇩",
    "language": "اندونزیایی/انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://en.antaranews.com"
  },
  {
    "name": "The Times",
    "nameFa": "تایمز لندن",
    "url": "https://openrss.org/thetimes.co.uk",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.thetimes.co.uk"
  },
  {
    "name": "USA Today",
    "nameFa": "یو‌اس‌ای تودی",
    "url": "http://rssfeeds.usatoday.com/usatoday-NewsTopStories",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.usatoday.com"
  },
  {
    "name": "Chicago Tribune",
    "nameFa": "شیکاگو تریبیون",
    "url": "https://www.chicagotribune.com/arc/outboundfeeds/rss/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.chicagotribune.com"
  },
  {
    "name": "LA Times",
    "nameFa": "لس آنجلس تایمز",
    "url": "https://www.latimes.com/world/rss2.0.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.latimes.com"
  },
  {
    "name": "Boston Globe",
    "nameFa": "بوستون گلوب",
    "url": "https://www.bostonglobe.com/rss/news",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.bostonglobe.com"
  },
  {
    "name": "Toronto Star",
    "nameFa": "تورنتو استار",
    "url": "https://www.thestar.com/feeds.articles.news.rss",
    "country": "CA",
    "countryName": "کانادا",
    "flag": "🇨🇦",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.thestar.com"
  },
  {
    "name": "Globe and Mail",
    "nameFa": "گلوب اند میل",
    "url": "https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/world/",
    "country": "CA",
    "countryName": "کانادا",
    "flag": "🇨🇦",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.theglobeandmail.com"
  },
  {
    "name": "Sydney Morning Herald",
    "nameFa": "سیدنی مورنینگ هرالد",
    "url": "https://www.smh.com.au/rss/feed.xml",
    "country": "AU",
    "countryName": "استرالیا",
    "flag": "🇦🇺",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.smh.com.au"
  },
  {
    "name": "Straits Times",
    "nameFa": "استریتس تایمز",
    "url": "https://www.straitstimes.com/news/world/rss.xml",
    "country": "SG",
    "countryName": "سنگاپور",
    "flag": "🇸🇬",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.straitstimes.com"
  },
  {
    "name": "Times of India",
    "nameFa": "تایمز هند",
    "url": "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms",
    "country": "IN",
    "countryName": "هند",
    "flag": "🇮🇳",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://timesofindia.indiatimes.com"
  },
  {
    "name": "TechRadar",
    "nameFa": "تک رادار",
    "url": "https://www.techradar.com/rss",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.techradar.com"
  },
  {
    "name": "Digital Trends",
    "nameFa": "دیجیتال ترندز",
    "url": "https://www.digitaltrends.com/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.digitaltrends.com"
  },
  {
    "name": "Mashable",
    "nameFa": "مشبل",
    "url": "https://mashable.com/feed",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://mashable.com"
  },
  {
    "name": "PCMag",
    "nameFa": "پی‌سی مگ",
    "url": "https://www.pcmag.com/rss/news",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.pcmag.com"
  },
  {
    "name": "Tom's Hardware",
    "nameFa": "تامز هاردویر",
    "url": "https://www.tomshardware.com/rss.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.tomshardware.com"
  },
  {
    "name": "The Next Web",
    "nameFa": "نکست وب",
    "url": "https://thenextweb.com/feed",
    "country": "NL",
    "countryName": "هلند",
    "flag": "🇳🇱",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://thenextweb.com"
  },
  {
    "name": "Gigaom",
    "nameFa": "گیگا اوم",
    "url": "https://gigaom.com/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://gigaom.com"
  },
  {
    "name": "TechSpot",
    "nameFa": "تک اسپات",
    "url": "https://www.techspot.com/backend.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.techspot.com"
  },
  {
    "name": "Neowin",
    "nameFa": "نئووين",
    "url": "https://www.neowin.net/news/rss/",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.neowin.net"
  },
  {
    "name": "Space.com",
    "nameFa": "اسپیس",
    "url": "https://www.space.com/feeds/all",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "science",
    "categoryFa": "علمی",
    "website": "https://www.space.com"
  },
  {
    "name": "Business Standard",
    "nameFa": "بیزنس استاندارد",
    "url": "https://www.business-standard.com/rss/latest.rss",
    "country": "IN",
    "countryName": "هند",
    "flag": "🇮🇳",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.business-standard.com"
  },
  {
    "name": "Economic Times",
    "nameFa": "اکونومیک تایمز",
    "url": "https://economictimes.indiatimes.com/rssfeedsdefault.cms",
    "country": "IN",
    "countryName": "هند",
    "flag": "🇮🇳",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://economictimes.indiatimes.com"
  },
  {
    "name": "Business Times",
    "nameFa": "بیزنس تایمز",
    "url": "https://www.businesstimes.com.sg/rss/top-stories",
    "country": "SG",
    "countryName": "سنگاپور",
    "flag": "🇸🇬",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.businesstimes.com.sg"
  },
  {
    "name": "Nikkei Asia",
    "nameFa": "نیکی آسیا",
    "url": "https://asia.nikkei.com/rss/feed/nar",
    "country": "JP",
    "countryName": "ژاپن",
    "flag": "🇯🇵",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://asia.nikkei.com"
  },
  {
    "name": "Financial Post",
    "nameFa": "فایننشال پست",
    "url": "https://financialpost.com/feed/",
    "country": "CA",
    "countryName": "کانادا",
    "flag": "🇨🇦",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://financialpost.com"
  },
  {
    "name": "Investopedia",
    "nameFa": "اینوستوپدیا",
    "url": "https://www.investopedia.com/feed-4769785",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.investopedia.com"
  },
  {
    "name": "Kiplinger",
    "nameFa": "کپلر",
    "url": "https://www.kiplinger.com/index.rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.kiplinger.com"
  },
  {
    "name": "Finance Magnates",
    "nameFa": "فایننس مگنتس",
    "url": "https://www.financemagnates.com/feed/",
    "country": "INT",
    "countryName": "بین‌المللی",
    "flag": "🌐",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.financemagnates.com"
  },
  {
    "name": "CoinDesk",
    "nameFa": "کوین دسک",
    "url": "https://www.coindesk.com/arc/outboundfeeds/rss/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.coindesk.com"
  },
  {
    "name": "CoinTelegraph",
    "nameFa": "کوین تلگراف",
    "url": "https://cointelegraph.com/rss",
    "country": "INT",
    "countryName": "بین‌المللی",
    "flag": "🌐",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://cointelegraph.com"
  },
  {
    "name": "AEI",
    "nameFa": "مؤسسه امریکن انترپرایز",
    "url": "https://www.aei.org/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.aei.org"
  },
  {
    "name": "Heritage Foundation",
    "nameFa": "بنیاد هریتیج",
    "url": "https://www.heritage.org/rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.heritage.org"
  },
  {
    "name": "Center for American Progress",
    "nameFa": "مرکز پیشرفت آمریکا",
    "url": "https://www.americanprogress.org/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.americanprogress.org"
  },
  {
    "name": "Cato Institute",
    "nameFa": "مؤسسه کاتو",
    "url": "https://www.cato.org/rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.cato.org"
  },
  {
    "name": "Hudson Institute",
    "nameFa": "مؤسسه هادسون",
    "url": "https://www.hudson.org/rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.hudson.org"
  },
  {
    "name": "Washington Institute",
    "nameFa": "مؤسسه واشینگتن",
    "url": "https://www.washingtoninstitute.org/rss.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.washingtoninstitute.org"
  },
  {
    "name": "Middle East Institute",
    "nameFa": "مؤسسه خاورمیانه",
    "url": "https://www.mei.edu/rss.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.mei.edu"
  },
  {
    "name": "USIP",
    "nameFa": "مؤسسه صلح آمریکا",
    "url": "https://www.usip.org/rss.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.usip.org"
  },
  {
    "name": "Aspen Institute",
    "nameFa": "مؤسسه آسپن",
    "url": "https://www.aspeninstitute.org/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.aspeninstitute.org"
  },
  {
    "name": "Bruegel",
    "nameFa": "مؤسسه بروسل",
    "url": "https://www.bruegel.org/feed/",
    "country": "BE",
    "countryName": "بلژیک",
    "flag": "🇧🇪",
    "language": "انگلیسی",
    "category": "analysis",
    "categoryFa": "تحلیلی",
    "website": "https://www.bruegel.org"
  },
  {
    "name": "ESPN",
    "nameFa": "ای‌اس‌پی‌ان",
    "url": "https://www.espn.com/espn/rss/news",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "sports",
    "categoryFa": "ورزشی",
    "website": "https://www.espn.com"
  },
  {
    "name": "ESPN",
    "nameFa": "ای‌اس‌پی‌ان",
    "url": "https://www.espn.com/espn/rss/nfl/news",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "sports",
    "categoryFa": "ورزشی",
    "website": "https://www.espn.com"
  },
  {
    "name": "Sky Sports",
    "nameFa": "اسکای اسپورتس",
    "url": "https://www.skysports.com/rss/12040",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "sports",
    "categoryFa": "ورزشی",
    "website": "https://www.skysports.com"
  },
  {
    "name": "BBC Sport",
    "nameFa": "بی‌بی‌سی اسپورت",
    "url": "https://newsrss.bbc.co.uk/rss/sportonline_uk_edition/front_page/rss.xml",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "sports",
    "categoryFa": "ورزشی",
    "website": "https://www.bbc.com/sport"
  },
  {
    "name": "Goal.com",
    "nameFa": "گل",
    "url": "https://www.goal.com/en/feeds/news",
    "country": "INT",
    "countryName": "بین‌المللی",
    "flag": "🌐",
    "language": "انگلیسی",
    "category": "sports",
    "categoryFa": "ورزشی",
    "website": "https://www.goal.com"
  },
  {
    "name": "The Athletic",
    "nameFa": "اتلتیک",
    "url": "https://theathletic.com/rss",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "sports",
    "categoryFa": "ورزشی",
    "website": "https://theathletic.com"
  },
  {
    "name": "Sports Illustrated",
    "nameFa": "اسپورتس ایلوستریتد",
    "url": "https://www.si.com/.rss/full/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "sports",
    "categoryFa": "ورزشی",
    "website": "https://www.si.com"
  },
  {
    "name": "Marca",
    "nameFa": "مارکا",
    "url": "https://e00-marca.uecdn.es/rss/portada.xml",
    "country": "ES",
    "countryName": "اسپانیا",
    "flag": "🇪🇸",
    "language": "اسپانیایی",
    "category": "sports",
    "categoryFa": "ورزشی",
    "website": "https://www.marca.com"
  },
  {
    "name": "AS",
    "nameFa": "آس",
    "url": "https://as.com/rss/tags/ultimas_noticias.xml",
    "country": "ES",
    "countryName": "اسپانیا",
    "flag": "🇪🇸",
    "language": "اسپانیایی",
    "category": "sports",
    "categoryFa": "ورزشی",
    "website": "https://as.com"
  },
  {
    "name": "L'Equipe",
    "nameFa": "اکیپ",
    "url": "https://www.lequipe.fr/rss/actu_rss.xml",
    "country": "FR",
    "countryName": "فرانسه",
    "flag": "🇫🇷",
    "language": "فرانسوی",
    "category": "sports",
    "categoryFa": "ورزشی",
    "website": "https://www.lequipe.fr"
  },
  {
    "name": "Gazzetta dello Sport",
    "nameFa": "گاتزتا دلو اسپورت",
    "url": "https://www.gazzetta.it/rss/home.xml",
    "country": "IT",
    "countryName": "ایتالیا",
    "flag": "🇮🇹",
    "language": "ایتالیایی",
    "category": "sports",
    "categoryFa": "ورزشی",
    "website": "https://www.gazzetta.it"
  },
  {
    "name": "Times of Israel",
    "nameFa": "تایمز اسرائیل",
    "url": "https://www.timesofisrael.com/feed/",
    "country": "IL",
    "countryName": "اسرائیل",
    "flag": "🇮🇱",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.timesofisrael.com"
  },
  {
    "name": "The National",
    "nameFa": "نشنال",
    "url": "https://www.thenationalnews.com/rss.xml",
    "country": "AE",
    "countryName": "امارات",
    "flag": "🇦🇪",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.thenationalnews.com"
  },
  {
    "name": "Asharq Al-Awsat",
    "nameFa": "الشرق الاوسط",
    "url": "https://english.aawsat.com/rss",
    "country": "SA",
    "countryName": "عربستان",
    "flag": "🇸🇦",
    "language": "عربی/انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://english.aawsat.com"
  },
  {
    "name": "Al-Ahram",
    "nameFa": "الاهرام",
    "url": "https://gate.ahram.org.eg/rss/1.xml",
    "country": "EG",
    "countryName": "مصر",
    "flag": "🇪🇬",
    "language": "عربی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://gate.ahram.org.eg"
  },
  {
    "name": "The Daily Star",
    "nameFa": "دیلی استار",
    "url": "https://openrss.org/dailystar.com.lb",
    "country": "LB",
    "countryName": "لبنان",
    "flag": "🇱🇧",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.dailystar.com.lb"
  },
  {
    "name": "Bangkok Post",
    "nameFa": "بانکوک پست",
    "url": "https://www.bangkokpost.com/rss/data/most-recent.xml",
    "country": "TH",
    "countryName": "تایلند",
    "flag": "🇹🇭",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.bangkokpost.com"
  },
  {
    "name": "Jakarta Post",
    "nameFa": "جاکارتا پست",
    "url": "https://www.thejakartapost.com/rss",
    "country": "ID",
    "countryName": "اندونزی",
    "flag": "🇮🇩",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.thejakartapost.com"
  },
  {
    "name": "Manila Bulletin",
    "nameFa": "مانیلا بولتن",
    "url": "https://mb.com.ph/rss",
    "country": "PH",
    "countryName": "فیلیپین",
    "flag": "🇵🇭",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://mb.com.ph"
  },
  {
    "name": "The Star",
    "nameFa": "استار مالزی",
    "url": "https://www.thestar.com.my/rss/news/world",
    "country": "MY",
    "countryName": "مالزی",
    "flag": "🇲🇾",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://www.thestar.com.my"
  },
  {
    "name": "Live Science",
    "nameFa": "لایو ساینس",
    "url": "https://www.livescience.com/feeds/all",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "science",
    "categoryFa": "علمی",
    "website": "https://www.livescience.com"
  },
  {
    "name": "ScienceDaily",
    "nameFa": "ساینس دیلی",
    "url": "https://www.sciencedaily.com/rss/all.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "science",
    "categoryFa": "علمی",
    "website": "https://www.sciencedaily.com"
  },
  {
    "name": "ScienceDaily",
    "nameFa": "ساینس دیلی",
    "url": "https://www.sciencedaily.com/rss/top/technology.xml",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "tech",
    "categoryFa": "فناوری",
    "website": "https://www.sciencedaily.com"
  },
  {
    "name": "Phys.org",
    "nameFa": "فیز دات اورگ",
    "url": "https://phys.org/rss-feed/",
    "country": "INT",
    "countryName": "بین‌المللی",
    "flag": "🌐",
    "language": "انگلیسی",
    "category": "science",
    "categoryFa": "علمی",
    "website": "https://phys.org"
  },
  {
    "name": "Medical News Today",
    "nameFa": "مدیکال نیوز تودی",
    "url": "https://www.medicalnewstoday.com/rss",
    "country": "GB",
    "countryName": "بریتانیا",
    "flag": "🇬🇧",
    "language": "انگلیسی",
    "category": "science",
    "categoryFa": "علمی",
    "website": "https://www.medicalnewstoday.com"
  },
  {
    "name": "Healthline",
    "nameFa": "هلث لاین",
    "url": "https://www.healthline.com/feed",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "science",
    "categoryFa": "علمی",
    "website": "https://www.healthline.com"
  },
  {
    "name": "SciTechDaily",
    "nameFa": "سای‌تک دیلی",
    "url": "https://scitechdaily.com/feed/",
    "country": "US",
    "countryName": "آمریکا",
    "flag": "🇺🇸",
    "language": "انگلیسی",
    "category": "science",
    "categoryFa": "علمی",
    "website": "https://scitechdaily.com"
  },
  {
    "name": "EUobserver",
    "nameFa": "ای‌یو آبزرور",
    "url": "https://euobserver.com/rss",
    "country": "BE",
    "countryName": "بلژیک",
    "flag": "🇧🇪",
    "language": "انگلیسی",
    "category": "general",
    "categoryFa": "عمومی",
    "website": "https://euobserver.com"
  }
];
